from __future__ import annotations

BLUE_COLLAR_KEYWORDS = {
    "ac repair",
    "air conditioning",
    "appliance repair",
    "asphalt",
    "auto repair",
    "carpet cleaning",
    "concrete",
    "construction",
    "contractor",
    "deck",
    "demolition",
    "drywall",
    "electrician",
    "excavation",
    "fence",
    "flooring",
    "foundation",
    "garage door",
    "glass",
    "gutter",
    "handyman",
    "hauling",
    "hvac",
    "insulation",
    "janitorial",
    "landscaping",
    "lawn care",
    "locksmith",
    "masonry",
    "mechanic",
    "metal",
    "moving",
    "painting",
    "pest control",
    "plumber",
    "plumbing",
    "pool service",
    "pressure washing",
    "remodeling",
    "restoration",
    "roofing",
    "septic",
    "siding",
    "tree service",
    "welding",
    "window",
}

TEXAS_SIGNALS = {
    "tx",
    "texas",
    "san antonio",
    "austin",
    "dallas",
    "fort worth",
    "houston",
    "el paso",
    "corpus christi",
    "laredo",
    "new braunfels",
    "boerne",
    "seguin",
    "schertz",
    "converse",
    "helotes",
    "leon valley",
}

CONTACT_PATH_HINTS = (
    "contact",
    "about",
    "team",
    "staff",
    "service",
    "services",
    "location",
    "locations",
    "quote",
    "estimate",
)

SKIP_EMAIL_PREFIXES = {
    "abuse",
    "admin",
    "example",
    "hostmaster",
    "noreply",
    "no-reply",
    "postmaster",
    "privacy",
    "support",
    "webmaster",
}

GENERIC_EMAIL_PREFIXES = {
    "admin",
    "billing",
    "careers",
    "contact",
    "enquiries",
    "general",
    "hello",
    "help",
    "info",
    "inquiries",
    "jobs",
    "marketing",
    "media",
    "office",
    "sales",
    "service",
    "support",
    "team",
}
